---
title: Excess consumption of dietary advanced glycation end products induce changes in gut microbiota which is associated with inflammation
draft: false
authors: []
event: '12th International Symposium on the Maillard Reaction 2015'
event_url: http://www.imars.org/online/
location: Tokyo, Japan
summary: "12th International Symposium on the Maillard Reaction 2015"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2015-09-30T08:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2015-06-15"

links:
#- icon: github
#  icon_pack: fab
#  name: materials
#  url: 

categories:
#  - talks
tags:
  - advanced glycation endproducts
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Abstract:

Main Objectives: It is thought that over-consumption of food high in Advanced glycation end-products (AGEs) may activate pathways involved in chronic disease progression thereby exacerbating pre-existing pathology. The majority of diet-derived AGEs escape digestion and reach the colon, and previous studies suggest that dietary AGEs can modulate the gut microbiota, though a comprehensive profiling of gut microbiota using metagenomics has not been previously performed. The aim of this study was to characterise the effects of dietary AGEs on gut microbiota profile and inflammation.

Strategy and Methods: C57BL6/J mice (n=10/group) were randomised to receive a diet low in AGEs (unbaked rodent chow, AIN93G) or a diet high in AGEs (baked AIN93G rodent chow, 160 degrees C for 1h, resulting in a 5-fold higher AGE content) for 24 weeks. 16S rRNA sequencing was used to profile the gut microbiome. Inflammation was determined by plasma monocyte chemoattractant protein (MCP)-1 measured by ELISA. Bacterial translocation to the circulation was measured by plasma lipopolysaccharide (LPS) using the Limulus Amebocyte Lysate (LAL) assay. Tight junction proteins ZO-1 and occludin were determined in the ileum and jejenum by qPCR.  

Main Results: Chronic consumption of excess dietary AGEs by healthy mice led to an increase in cecal bacterial diversity compared to the low AGE diet. Analysis of the operational taxonomic unit (OTU) at the family level showed an increase in Bacteroidaceae and Heliobacteraceae and a decrease in Lachnospiraceae and Saccharibacteria. There was also a decrease in Akkermansia muciniphila species and genus Ruminococcus. Plasma MCP-1 and LPS were increased after high AGE feeding. ZO-1 and occludin gene expression were downregulated in ileum and jejenum respectively.

Conclusions: These novel data indicate that excess dietary intake of AGEs alters the gut microbiome, induces intestinal permeability and bacterial translocation to the circulation, supporting the notion that diet-derived AGEs can promote inflammation.
