---
title: "Metabolic effects of resistant starch type 2: a systematic literature review and meta-analysis of randomised controlled trials" 
draft: false
authors: []
event: "Nutrition Society of Australia 43rd Annual Scientific Meeting"
event_url: https://nsameeting.asn.au
location: Canberra, Australia
summary: "Nutrition Society of Australia 43rd Annual Scientific Meeting"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2018-11-29T08:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2018-11-29"

links:
#- icon: file-alt
#  icon_pack: fa
#  name: Published Abstract
#  url: "pdf/conference/2018_ANZSN.pdf"

- icon: slideshare
  icon_pack: fab
  name: Slides
  url: "slides/2018-NSA.pdf"

- icon: link
  icon_pack: fa
  name: Published Paper
  url: "publication/2019_Snelson_RS-SLR/"

categories:
#  - talks
tags:
  - resistant starch
  - metabolic syndrome
  - diabetes
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Abstract:

Published evidence exploring effects of dietary resistant starch (RS) on cardiometabolic health is inconsistent. This review aimed to investigate the effect of dietary RS type 2 (RS2) supplementation on body weight, satiety ratings, fasting plasma glucose, HbA1c, insulin resistance and lipid levels in healthy individuals and those with overweight/obesity, the metabolic syndrome (MetS) or type 2 diabetes mellitus (T2DM). Five electronic databases were searched for Randomised Controlled Trials (RCTs) published in English between 1982-2017, investigating the effect of dietary RS2 supplementation on cardiometabolic health.
Trials were eligible for inclusion if they reported RCTs involving humans where at least one group received ≥10 grams of RS2 per day for ≥1 week, and measured body weight, satiety, glucose and/or lipid metabolic outcomes. Twenty RCTs involving 569 participants were included. RS2 supplementation significantly reduced serum triacylglycerol concentrations (Mean difference= -0.11 mmol/L; 95% CI -0.18, -0.04, P=0.002) in healthy individuals (n=227) and reduced body weight (MD= -1.29kg; 95% CI -2.40, -0.17, P=0.02) in people with T2DM (n=90), but had no effect on appetite, fasting plasma glucose, HbA1c, HOMA-IR, total cholesterol, LDL-cholesterol or HDL-cholesterol in any patient sub-groups. Most studies had a moderate-high risk of bias, were of short duration and contained small sample sizes. High quality, long-term trials are required to determine the efficacy of RS2 supplementation as a dietary strategy in the management of metabolic disease.