---
title: "Dietary Resistant Starch Protects Against Diabetic Nephropathy by Inhibition of Complement" 
draft: false
authors: []
event: "54th Australian and New Zealand Society of Nephrology Annual Scientific Meeting"
event_url: https://www.nephrology.edu.au/
location: Sydney, Australia
summary: "54th Australian and New Zealand Society of Nephrology Annual Scientific Meeting"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2018-09-08T08:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2018-09-08"

links:
- icon: file-alt
  icon_pack: fa
  name: Published Abstract
  url: "pdf/conference/2018_ANZSN.pdf"


categories:
#  - talks
tags:
  - complement activation
  - resistant starch
  - diabetic kidney disease
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Abstract:

Aim
To investigate immune mechanisms by which resistant starch (RS) supplementation may be protective against diabetic nephropathy.

Background
Activation of complement occurs in diabetic nephropathy. C5a is a downstream complement component that activates the innate immune system contributing to inflammation. Dietary RS may be nephro-protective, however the effects of dietary RS on complement activation and the innate immune system have not been explored. 

Methods
Six week old non-diabetic mice (db/h), diabetic mice (db/db) and db/db mice on a regular chow diet supplemented with 25% RS (dbdb+RS) were maintained for ten weeks. 24-hour urine was collected for albumin and C5a measurement by ELISA. Kidneys were digested and enriched for leukocytes using Percoll gradient. Cells were stained with BV786-CD45, AF700-CD11b, PE-Cy7-CD11c, BV711-Siglec F, BV605-Ly6C, PE-CD86, FITC-C5aR antibodies and flow cytometry was performed.

Results
Diabetes was associated with an increase in albuminuria (28.0±6.5 vs 411.3±275.8µg/24h, P<0.001, dbh vs dbdb), which was reduced in diabetic mice receiving RS supplementation (411.3±275.8 vs 125.6±37.3µg/24h, P<0.01, dbdb vs dbdb+RS). Urinary C5a excretion was increased by diabetes (92.6±17.6 vs 1324.0±429.7pg/24h, P<0.001, dbh vs dbdb) and decreased by RS (1324.0±429.7 vs 577.7±123.1pg/24h, P<0.05, dbdb vs dbdb+RS). In diabetes there was an increase in CD86 MFI (a marker of activation) on infiltrating macrophages (CD45+ CD11b+ CD11c- Siglec F- Ly6C hi), which was attenuated with RS (3.7±1.8 vs 1.5±1.0 fold change to dbh, P<0.05, dbdb vs dbdb+RS). Furthermore, infiltrating macrophages were more likely to be positive for C5aR with diabetes (4.8±3.9 vs 54.0±27.8%, P<0.001, dbh vs dbdb), which RS supplementation reduced (54.0±27.8 vs 11.7±4.2%, P<0.01, dbdb vs dbdb+RS).

Conclusions
These studies support the notion that dietary RS is protective against renal disease via inhibition of complement.