---
title: "Resistant Starch Ameliorates Advanced Glycation Endproduct-Induced Albuminuria ina Mouse Model of Type 2 Diabetes" 
draft: false
authors: []
event: '15th Asian Pacific Congress of Nephrology & 52nd Australian and New Zealand Society of Nephrology ASM'
event_url: https://apcn2016.com.au/
location: Perth, Australia
summary: "15th Asian Pacific Congress of Nephrology & 52nd Australian and New Zealand Society of Nephrology ASM"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2016-09-18T08:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2016-09-18"

links:
- icon: file-alt
  icon_pack: fa
  name: Published Abstract
  url: "pdf/conference/2016_ANZSN.pdf"

categories:
#  - talks
tags:
  - advanced glycation endproducts
  - resistant starch
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Abstract:

Aim: To investigate whether excess consumption of dietary advanced glycation endproducts (AGEs) cause gut dysbiosis, exacerbating renal injury in a type 2 diabetes model.


Background: Long-term excess intake of dietary AGEs contributes to chronic renal injury. Recent research implicates gut dysbiosis in the progression of diabetic nephropathy. However, the role of dietary AGEs in gut dysbiosis and renal dysfunction in the context of diabetes has not yet been explored. 


Methods: Six week old diabetic (db/db) and non-diabetic (db/h) mice were randomised (n=12/group) to receive a low AGE (LAGE, unbaked rodent chow) or a high AGE diet (HAGE, baked at 160°C for 1 hour), with or without resistant starch (RS) for 10 weeks.  24-hour urine was collected for the assessment of albuminuria. Intestinal permeability was assessed in-vivo by the clearance of FITC-labelled dextran (500mg/kg body weight).


Results: The high AGE diet exacerbated albuminuria in db/db mice (874.4±154.8 vs 536.2±96.53µg/24h, P<0.05, db/db HAGE vs db/db LAGE), and this AGE-induced increase in albuminuria was attenuated by RS (874.4±154.8 vs 515.5±71.88µg/24h, P<0.05, db/db HAGE vs db/db HAGE + RS). Db/db mice had greater gut permeability compared to db/h mice (2.38±0.32 vs 1.05±0.11µg/ml, P<0.01, db/db LAGE vs db/h LAGE). Furthermore, the high AGE diet tended to increase gut permeability of db/db mice (3.43±0.43 vs 2.38±0.32µg/ml, P=0.06, db/db HAGE vs db/db LAGE), an effect not observed in RS-fed db/db mice.


Conclusions: A high AGE diet led to increased intestinal permeability, which was associated with worsening albuminuria in db/db mice. Resistant starch was protective against high AGE induced albuminuria in db/db mice. These preliminary studies support the notion that dietary AGEs contribute to renal disease via alterations in gut homeostasis.