---
title: "Resistant Starch Ameliorates Advanced Glycation Endproduct-Induced Albuminuria in a Mouse Model of Type 2 Diabetes" 
draft: false
authors: []
event: "53rd Annual Meeting of the European Association for the Study of Diabetes"
event_url: http://www.easd.org/
location: Lisbon, Portugal
summary: "53rd Annual Meeting of the European Association for the Study of Diabetes"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2017-09-14T08:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2017-09-14"

links:
- icon: file-alt
  icon_pack: fa
  name: Published Abstract
  url: "pdf/conference/2017_EASD_486.pdf"


categories:
#  - talks
tags:
  - advanced glycation endproducts
  - resistant starch
  - diabetic kidney disease
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Abstract:

Background and Aim: Long-term excess intake of dietary advanced glycation endproducts (AGEs) contributes to chronic renal injury. Recent research implicates gut dysbiosis in the progression of diabetic nephropathy, however, the role of dietary AGEs in gut dysbiosis and renal injury in the context of diabetes has not yet been explored. The aim of this study was to investigate whether excess consumption of dietary AGEs cause gut dysbiosis, exacerbating renal injury in a mouse model of type 2 diabetes. A secondary aim was to elucidate whether a high fibre diet (resistant starch), may be protective against diabetic nephropathy via altering gut homeostasis. Methods: Six week old diabetic mice (db/db) (BKS.Cg-Dock7m+/+Leprdb/J) on a C57BL/KsJ background and age-matched non-diabetic control mice (db/m) were randomised (n=12/group) to receive a low AGE (LAGE, unbaked rodent chow) or a high AGE diet (HAGE, baked at 160°C for 1 hour), with or without 25% resistant starch (RS) for 10 weeks. All diets were isocaloric. 24-hour urine was collected for the assessment of albuminuria. At 15 weeks of age, mice were fasted and an oral glucose tolerance test (2g/kg lean body mass) was performed. At 16 weeks of age, intestinal permeability was assessed in vivo by the clearance of FITC-labelled dextran (500mg/kg body weight). Glycated haemoglobin was assessed using a Roche cobas b101 analyser.

Results: The high AGE diet exacerbated albuminuria in db/db mice (874.4±154.8 vs 536.2±96.5μg/24h, P<0.05, db/db HAGE vs db/db LAGE), and this AGE-induced increase in albuminuria was attenuated by RS (874.4±154.8 vs 515.5±71.9μg/24h, P<0.05, db/db HAGE vs db/db HAGE + RS). Db/db mice had increased gut permeability compared to db/m mice (2.38±0.32 vs 1.05±0.11μg/ml, P<0.01, db/db LAGE vs db/m LAGE). Furthermore, the high AGE diet increased gut permeability of db/db mice (3.43±0.43 vs 2.38±0.32μg/ml, P=0.06, db/db HAGE vs db/db LAGE), an effect not observed in RS-fed db/db mice (2.38±0.32 vs 2.86±0.35μg/ml, P>0.05, db/db LAGE vs db/db LAGE+RS). Following OGTT, db/db mice had a higher glucose AUC (74.08±5.98 vs 17.54±2.32 mmol/L x min, P<0.05, db/db LAGE vs db/m LAGE) and glycated haemoglobin (10.47±1.96 vs 4.06±0.12, P<0.05, db/db LAGE vs db/m LAGE) compared to db/m mice. Neither the high AGE diet nor the resistant starch supplemented diets influenced glycaemic control in db/db or db/m mice, as reflected by OGTT AUC (74.08±5.98 vs 75.29±6.45 vs 75.29±6.45 vs 72.64±7.16 mmol/L x min, P>0.05, db/db LAGE vs db/db LAGE+RS vs db/db HAGE vs db/db HAGE+RS), or glycated haemoglobin (10.61±0.46 vs 9.65±0.55 vs 10.98±0.67 vs 10.58±0.67 % glycated haemoglobin, P>0.05, db/db LAGE vs db/db LAGE+RS vs db/db HAGE vs db/db HAGE+RS).

Conclusions: A high AGE diet led to increased intestinal permeability, which was associated with worsening albuminuria in db/db mice. Resistant starch was protective against high AGE induced albuminuria in db/db mice, effects which are not dependant on changes in glucose homeostasis. These preliminary studies support the notion that dietary AGEs contribute to renal disease via alterations in gut homeostasis and suggest a potential role for resistant starch as a renoprotective agent.