---
title: "Diabetes and the gut microbiota: sorting through the crap" 
draft: false
authors: []
event: "Australasian Diabetes Congress 2019"
event_url: http://www.diabetescongress.com.au/ 
location: Sydney, Australia
summary: "Australasian Diabetes Congress 2019"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2019-08-22T09:00:00Z"
#date_end: "2019-10-02T12:00:00Z"
all_day: true
publishdate: "2019-08-01"

links:
- icon: slideshare
  icon_pack: fab
  name: Slides
  url: "talks/2019_ADEA_microbiome.pdf"       #<-can add slides via this.

# - icon: twitter
#   icon_pack: fab
#   name: Follow
#   url: https://twitter.com/matt_snelson


#- icon: slideshare
#  icon_pack: fab
#  name: "Nic's Slides"
#  url: "#TODO"       #<-can add slides via this. 
 
   
- icon: user-tie
  icon_pack: fa
  name: Invited Speaker
  url: "talk/2019-ADC-3/"

#- icon: file-alt
#  icon_pack: fa
#  name: Published Abstract
#  url: ""



categories:
#  - talks
tags:
  - diabetes
  - gut microbiota
lastmod: '2019-06-16T02:20:01-07:00'
featured: no
image:
  caption: ""
  focal_point: ""
  preview_only: no
projects: []
---

#### Slides:

[My Presentation](pdf/2019_ADEA_microbiome.pdf).

[Dr Nicole Kellow's Presentation](pdf/2019_ADEA_NK.pdf).


#### Abstract:

There has been a recent explosion in research exploring the role of the microbiota in many disease states, including diabetes and metabolic disorders, fuelled by technological improvements and a reduction in the cost of microbiota sequencing. This session will provide an overview of the composition and function of the gut microbiota with particular relevance given to the role of the microbiota in diabetes and metabolic disorders. Key takeaways will include an understanding of how the microbiota is measured and the relative merits of different techniques, an appreciation of the common visualisations that are used to display the highly multidimensional data that are produced from microbiota sequencing, including the ability to interpret these findings, and an awareness of future directions of this field, in particular the relevance of microbiota testing to patient care within hospital and clinic settings. This symposium will also provide an overview of the lifestyle factors influencing the composition of the gut microbiota, including dietary prebiotics and probiotics, physical activity and sleep quality. Interventions used to favourably manipulate the composition of the gut microbiota in diabetes will be discussed, including interpretation of the evidence supporting the efficacy of these interventions. Following attendance at this symposium, participants will be able to provide practical and evidence-based advice about gut microbial measurement and manipulation to their patients with diabetes.
